export const projects = [
  {
    Title: "Project 1",
    Technologies: "Python, HTML, CSS, Machine Learning, Deep Learning",
    Frontend: "HTML, CSS, JavaScript",
    Backend: "Python",
    Availability: "Available to join immediately",
  },
  {
    Title: "Project 2",
    Technologies: "Java Spring Boot, Hibernate, MySQL",
    Frontend: "React JS",
    Backend: "Java, Spring Boot, Hibernate",
    Databases: "MySQL",
    Infrastructre: "Not specified",
    Availability:
      "Available to join within a week and open to relocate to Gurgaon",
  },
  {
    Title: "Project 3 ",
    Technologies: "Java, HTML, CSS, JavaScript",
    Frontend: "React, HTML, CSS",
    Backend: "Java, Python Django, Flask",
    Databases: "MySQL, MongoDB, Postgres",
    Infrastructre: "AWS, Azure OCR, Apache, Docker",
    Availability:
      "Available to join immediately and willing to relocate to Gurgaon",
  },
  {
    Title: "Project 4",
    Technologies: "Websockets, Redis, Channel layers",
    Frontend: "React",
    Backend: "Python Django, Django Rest",
    Databases: "MySQL",
    Infrastructre: "Not Mentioned",
    Availability: "Immediate or first/last week of October",
  },
  {
    Title: "Project 5",
    Technologies: "Python, Scrapy framework, MongoDB",
    Frontend: "React Native",
    Backend: "Python, Django",
    Databases: "MongoDB",
    Infrastructre: "Not Specified",
    Availability: "15-20 days, and is willing to relocate to Gurgaon",
  },
  {
    Title: "Project 6",
    Technologies: "Postman, Docker, Jenkins, Java, Spring Boot",
    Frontend: "React, Angular",
    Backend: "Spring Boot, Java",
    Infrastructre: "Postman, Docker, Jenkins",
    Availability:
      "Available to join in 10-15 days and willing to work from Gurgaon office.",
  },
  {
    Title: "Project 7",
    Technologies: "React JS, JWT Authentication, Local Storage",
    Frontend: "React JS, HTML, CSS, JavaScript",
    Backend: "Node JS",
    Databases: "MongoDB",
    Infrastructre: "Not Mentioned",
    Availability:
      "Available to join immediately, comfortable with relocating to Gurgaon",
  },
  {
    Title: "Project 8",
    Technologies: "Python, Django, API",
    Frontend: "No experience",
    Backend: "Python Django, API",
    Databases: "Not mentioned",
    Infrastructre: "Not mentioned",
    Availability: "Immediate",
  },
  {
    Title: "Project 9",
    Technologies: "React, Node, Java",
    Frontend: "React, Java, Angular, Node, JavaScript",
    Backend: "Node",
    Databases: "SQL",
    Availability:
      "Can join within one week; Comfortable with working from the office in Gurgaon",
  },
  {
    Title: "Project 10",
    Technologies:
      "React JS, Redux, HTML, CSS, Bootstrap, Material UI, Socket.io, Python Django",
    Frontend: "React JS, HTML, CSS, Bootstrap, Material UI",
    Backend: "Python Django",
    Availability:
      "Available to join within 30 days, comfortable working from office in Gurgaon",
  },
  {
    Title: "Project 11",
    Technologies: "React JS, Node JS, TNT database",
    Frontend: "HTML, CSS, JavaScript, React JS",
    Backend: "Node JS",
    Databases: "SQL, TNT",
    Infrastructre: "Not mentioned",
    Availability: "Ready to join soon and comfortable with Gurgaon office",
  },
  {
    Title: "Project 12",
    Technologies: "React JS, Mongo DB, MVC architecture",
    Frontend: "React JS",
    Backend: "Mongo DB",
    Databases: "Mongo DB",
    Infrastructre: "Not mentioned",
    Availability:
      "Available to join immediately and comfortable with relocating to Gurgaon",
  },
  {
    Title: "Project 13",
    Technologies: "Python, Java, Redis, caching, pagination, liquibase",
    Frontend: "React, Next js",
    Backend: "Python Django and Spring frameworks",
    Databases: "Not Specified",
    Infrastructre: "Not Specified",
    Availability: "Immediate joiner, based in NCR",
  },
  {
    Title: "Project 14",
    Technologies: "Python, AWS, JavaScript, Node JS, Docker",
    Frontend: "Angular, JavaScript, TypeScript",
    Backend: "Python, Java, Node JS, AWS Lambda functions",
    Databases: "SQL",
    Infrastructre: "Docker, AWS",
    Availability:
      "Can join within 30 days of offer and ready to relocate to Gurgaon",
  },
  {
    Title: "Project 15",
    Technologies: "Java, Spring Framework",
    Frontend: "React",
    Backend: "Python, Django, Java, Spring Framework",
    Databases: "Not Mentioned",
    Infrastructre: "Not Mentioned",
    Availability:
      "Earliest available date to join is 25th September 2023 and willing to work from Gurgaon office",
  },
  {
    Title: "Project 16",
    Technologies: "SQL, Cloud, Ecommerce, Haru, Spoke",
    Frontend: "React, Angular, Next.js",
    Backend: "SQL, MySQL, Oracle, Java, NoSQL",
    Databases: "SQL, MySQL, Oracle, NoSQL",
    Infrastructre: "Cloud platforms",
    Availability:
      "Available to join within a week and ready to move to Gurgaon office",
  },
  {
    Title: "Project 17",
    Technologies: "HTML, CSS, Node.js, SQL, MongoDB",
    Frontend: "HTML, CSS, React",
    Backend: "Node.js",
    Databases: "SQL, MongoDB",
    Infrastructre: "Not Mentioned",
    Availability: "Can join immediately within 3-4 days",
  },
  {
    Title: "Project 18",
    Technologies: "Java, Spring Boot, Angular, HTML, CSS, JavaScript, SQL",
    Frontend: "Angular, React, Next js",
    Backend: "Python Django, Spring",
    Databases: "SQL",
    Infrastructre: "HTTPD",
    Availability: "Immediate, comfortable with working from Gurgaon office",
  },
  {
    Title: "Project 19",
    Technologies: "Machine learning, Linear and Logistic Regression",
    Frontend: "React, Angular",
    Backend: "Python Django, Java Spring",
    Availability:
      "Available to start immediately and comfortable with working from Gurgaon office",
  },
  {
    Title: "Project 20",
    Technologies:
      "AWS, Node JS, Aurora DB, React, Python, TypeScript, JavaScript, CICD pipelines, ECS containers and topics",
    Frontend: "React",
    Backend: "Python, Node.js",
    Databases: "Aurora DB",
    Infrastructre: "AWS, ECS containers",
    Availability: "Immediate",
  },
  {
    Title: "Project 21",
    Technologies: "Django, Elasticview",
    Frontend: "React",
    Backend: "Django",
    Databases: "Not mentioned",
    Infrastructre: "Not mentioned",
    Availability:
      "Can join immediately within 5 days and is willing to commute to Gurgaon office",
  },
  {
    Title: "Project 22",
    Technologies: "Third Party APIs, Encryption and Decryption Algorithms",
    Frontend: "Angular, React, Next.js",
    Backend: "Node.js, Express",
    Databases: "Not Mentioned",
    Infrastructre: "Not Mentioned",
    Availability: "Immediate, ready to relocate to Gurgaon",
  },
  {
    Title: "Project 23",
    Technologies: "Java, React/TypeScript",
    Frontend: "React, Next JS, Google Auth",
    Backend: "Java Spring Framework",
    Databases: "Not Specified",
    Infrastructre: "Not Specified",
    Availability: "Immediately",
  },
  {
    Title: "Project 24",
    Technologies:
      "Java, Python, SQL, MongoDB, Mongoose, Passport, React and Express",
    Frontend: "React JS (Beginner level, Self-rated 7/10)",
    Backend: "Java, Python, SQL (Self-rated 7/10)",
    Databases: "MongoDB, SQL",
    Infrastructre: "No information provided",
    Availability:
      "Available to join for a full time position after January 2024, willing to work from Gurgaon office",
  },
  {
    Title: "Project 25",
    Technologies: "API, Event-based system",
    Frontend: "Reactjs",
    Backend: "Node JS, TypeScript, JavaScript",
    Databases: "Postgre SQL",
    Infrastructre: "Flutter",
    Availability:
      "Available to join in two months, open to discussing notice period compensation",
  },
  {
    Title: "Project 26",
    Technologies: "React, React Native",
    Frontend: "React, React Native",
    Backend: "Not experienced, but a quick learner",
    Databases: "Not mentioned",
    Infrastructre: "Not mentioned",
    Availability: "Immediate, ready to work from Gurgaon office",
  },
  {
    Title: "Project 27",
    Technologies: "Fitbit API, Isolation Forest Algorithm, Email Service",
    Frontend: "React",
    Backend: "Express, JavaScript",
    Databases: "Not Mentioned",
    Infrastructre: "Not Mentioned",
    Availability:
      "Available to join within two weeks and willing to relocate to Gurgaon",
  },
  {
    Title: "Project 28",
    Technologies: "Node JS, Puppeteer",
    Frontend: "JavaScript, React, Angular",
    Backend: "Node JS, Express, Python, Django",
    Infrastructre: "AWS",
    Availability: "Immediate",
  },
  {
    Title: "Project 29",
    Technologies: "Java, PostgreSQL",
    Frontend: "React",
    Backend: "Java",
    Databases: "PostgreSQL",
    Infrastructre: "Not Mentioned",
    Availability: "Immediately and is ready to relocate to Gurgaon",
  },
  {
    Title: "Project 30",
    Technologies: "React JS, Node JS, Express JS, MongoDB",
    Frontend: "HTML, CSS, JavaScript, jQuery",
    Backend: "PHP Codeigniter, Django",
    Databases: "MongoDB",
    Infrastructre: "Not specified",
    Availability: "One to two weeks, open for immediate joining if required",
  },
  {
    Title: "Project 31",
    Technologies: "Python Django, Flask, Spring Boot",
    Frontend: "ReactJS",
    Backend: "Python Django, Flask, Spring Boot",
    Availability: "Available to join in 30 days",
  },
  {
    Title: "Project 32",
    Technologies: "Node JS, JavaScript",
    Frontend: "Angular, React, Next js",
    Backend: "Node.js, Python Django",
    Databases: "Postman",
    Availability: "Immediate, comfortable with the office location in Gurgaon",
  },
  {
    Title: "Project 33",
    Technologies:
      "Machine Learning, Random Forest, Extra Trees Regressor, Light Gradient Boosting",
    Frontend: "React JS",
    Backend: "Node JS, Express JS",
    Databases: "Not mentioned",
    Infrastructre: "Not mentioned",
    Availability: "Within a week",
  },
  {
    Title: "Project 34",
    Technologies: "CA framework, Python APIs, React",
    Frontend: "React",
    Backend: "Python, Node.js",
    Databases: "Not mentioned",
    Infrastructre: "Not mentioned",
    Availability:
      "Rohan has a notice period of three months and is comfortable with relocating to Gurgaon.",
  },
  {
    Title: "Project 35",
    Technologies: "Node JS, TypeScript, MongoDB",
    Frontend: "Not Specified",
    Backend: "Node JS",
    Databases: "MongoDB",
    Infrastructre: "Not Specified",
    Availability: "Can join within 1.5-2 months",
  },
  {
    Title: "Project 36",
    Technologies: "Java, Retrofit, MVC pattern",
    Frontend: "React Native",
    Backend: "Java",
    Databases: "Not mentioned",
    Infrastructre: "Not mentioned",
    Availability: "Can join from July 2024 or January 2024",
  },
  {
    Title: "Project 37",
    Technologies: "Multicast graded CNN model, Hybrid recommender system",
    Frontend: "Not mentioned",
    Backend: "Back-end frameworks and APIs",
    Databases: "Not mentioned",
    Infrastructre: "Not mentioned",
    Availability: "27th/28th November",
  },
  {
    Title: "Project 38",
    Technologies:
      "Java, JavaScript, Android app development, Firebase, Node.js, MongoDB, Postman",
    Frontend: "React, HTML, CSS",
    Backend: "Node.js",
    Databases: "MongoDB, Firebase",
    Infrastructre: "Firebase",
    Availability: "Available to join in one week",
  },
  {
    Title: "Project 39",
    Technologies: "React JS, Node JS, HTML, CSS, JavaScript, EJS",
    Frontend: "React JS, HTML, CSS, JavaScript, EJS",
    Backend: "Node JS",
    Databases: "Not Mentioned",
    Infrastructre: "Not Mentioned",
    Availability:
      "Can join immediately, comfortable working from Gurgaon office",
  },
  {
    Title: "Project 40",
    Technologies:
      "Javascript, SQL, Report Labs, React, Python Django, Java, Spring Boot, MySQL",
    Frontend: "React, HTML, CSS, JavaScript",
    Backend: "Python Django, Java, Spring Boot",
    Databases: "MySQL, Sequel Lite",
    Availability: "Can join immediately and is comfortable working from office",
  },
  {
    Title: "Project 41",
    Technologies: "DuckDuckGo API, React Native, TypeScript",
    Frontend: "React Native",
    Backend: "Prayat",
    Databases: "Not mentioned",
    Infrastructre: "Not mentioned",
    Availability:
      "Available to join immediately and willing to work from Gurgaon office",
  },
  {
    Title: "Project 42",
    Technologies: "HTML, CSS, JavaScript, Tableau, Power BI, SQL, C++",
    Frontend: "HTML, CSS, JavaScript, React JS",
    Backend: "None mentioned",
    Databases: "SQL",
    Infrastructre: "None mentioned",
    Availability:
      "Can join within a week's notice and is comfortable with working from Gurgaon office",
  },
  {
    Title: "Project 43",
    Technologies:
      "Decentralized anomaly detection system, machine learning, attention mechanism",
    Frontend: "Angular, React, Next js",
    Backend: "Java, Spring Boot, JavaScript API",
    Databases: "Not mentioned",
    Infrastructre: "Not mentioned",
    Availability:
      "Available to start as soon as they get home and comfortable with the requirement of working from the office in Gurgaon",
  },
  {
    Title: "Project 44",
    Technologies: "Azure APIs and SAS fulfillment APIs",
    Backend: "Azure APIs and SAS fulfillment APIs",
    Databases: "SQL and NoSQL",
    Availability:
      "Can join in 15 days to one month and is comfortable with the arrangement of working from Gurgaon",
  },
  {
    Title: "Project 45",
    Technologies: "Java, AWS DynamoDB",
    Frontend: "Learning React.js",
    Backend: "Java",
    Databases: "AWS DynamoDB",
    Infrastructre: "AWS",
    Availability: "Immediate",
  },
  {
    Title: "Project 46",
    Technologies: "HTML, CSS, JavaScript, React JS, Python Django, Express",
    Frontend: "HTML, CSS, JavaScript, React JS",
    Backend: "Python Django, Express",
    Databases: "Not mentioned",
    Infrastructre: "Not mentioned",
    Availability:
      "Available to join immediately, comfortable in moving to Gurgaon",
  },
  {
    Title: "Project 47",
    Technologies:
      "PHP, JavaScript, jQuery, HTML, CSS, Bootstrap, MySQL, Node JS, Express JS, MongoDB",
    Frontend: "Bootstrap, JavaScript, jQuery",
    Backend: "PHP, Node.js, Express.js",
    Databases: "MySQL, MongoDB",
    Infrastructre: "Not Mentioned",
    Availability:
      "Available to join from October 222023, comfortable working from office in Gurgaon",
  },
  {
    Title: "Project 48",
    Technologies: "Python, Django, HTML, CSS, JavaScript",
    Frontend: "Angular, React, Next js",
    Backend: "Python Django, ASP.NET",
    Availability: "Immediately",
  },
  {
    Title: "Project 49",
    Technologies: "KN algorithm, Flutter, Dart, Firebase",
    Frontend: "React",
    Backend: "Node.js",
    Availability: "Immediate, ready to relocate to Gurgaon",
  },
  {
    Title: "Project 50",
    Technologies: "React, Node.js, API development",
    Frontend: "React",
    Backend: "Node.js",
    Databases: "MongoDB",
    Infrastructre: "Not mentioned",
    Availability:
      "Available to join from October and ready to move to Gurgaon office",
  },
  {
    Title: "Project 51",
    Technologies: "Machine Learning, Smart Analysis",
    Frontend: "Not Specified",
    Backend: "Django",
    Databases: "Not Specified",
    Infrastructre: "Not Specified",
    Availability: "Within 10 days of clearance of all rounds",
  },
  {
    Title: "Project 52",
    Technologies: "React, Django",
    Frontend: "React",
    Backend: "Django",
    Databases: "Not mentioned",
    Infrastructre: "Not mentioned",
    Availability: "Can join immediately and relocate to Gurgaon",
  },
  {
    Title: "Project 53",
    Technologies: "Angular, React, Next js, Python Django, Express JS",
    Frontend: "Angular, React, Next js",
    Backend: "Python Django, Express JS",
    Databases: "Not mentioned",
    Infrastructre: "Not mentioned",
    Availability:
      "Available to join as an intern immediately and full time from July 2024",
  },
  {
    Title: "Project 54",
    Technologies: "MongoDB, Express JS, Node JS, Java",
    Frontend: "Angular, React, Next js",
    Backend: "Python Django, Node.js",
    Databases: "MongoDB",
    Infrastructre: "Not mentioned",
    Availability:
      "Can join immediately and is comfortable with working from the office in Gurgaon",
  },
  {
    Title: "Project 55",
    Technologies: "Solidity",
    Frontend: "React.js",
    Backend: "Node.js",
    Databases: "MongoDB",
    Infrastructre: "Not provided",
    Availability:
      "Available to join in 10 days and willing to work from Gurgaon office",
  },
  {
    Title: "Project 56",
    Technologies: "NLTK library, Text BLOB and SVC",
    Frontend: "Not Mentioned",
    Backend: "Python",
    Databases: "Not Mentioned",
    Infrastructre: "Not Mentioned",
    Availability: "Immediate and ready to work from Gurgaon",
  },
  {
    Title: "Project 57",
    Technologies:
      "React Jsonschema, Material React Table, Promises, Batch Functions",
    Frontend: "React, CJS, Redux, HTML, CSS",
    Backend: "Python",
    Databases: "Unknown",
    Infrastructre: "Messenger, Python, and machine learning",
    Availability: "Available to join immediately",
  },
  {
    Title: "Project 58",
    Technologies: "TypeScript, Node.js",
    Frontend: "Angular",
    Backend: "Node.js",
    Databases: "Not Mentioned",
    Infrastructre: "Not Mentioned",
    Availability:
      "Available to join after 12 days of receiving the offer letter",
  },
  {
    Title: "Project 59",
    Technologies:
      "React, Angular, Next.js, Python, Django, Flask, MongoDB, MySQL",
    Frontend: "React, Angular, Next.js",
    Backend: "Python, Django, Flask",
    Databases: "MongoDB, MySQL",
    Infrastructre: "Not Provided",
    Availability:
      "Aman is comfortable with the work environment and location of the company. He is available to join if offered a position and is excited to be part of the team.",
  },
  {
    Title: "Project 60",
    Technologies: "React, Python, SQL, Java, C",
    Frontend: "React",
    Backend: "Python Flask",
    Databases: "SQL",
    Availability: "Immediately with zero days notice period",
  },
  {
    Title: "Project 61",
    Technologies: "HTML, Form groups, S3 bucket",
    Frontend: "Angular, React, Next.js",
    Backend: "Spring Boot, Django",
    Databases: "MySQL",
    Infrastructre: "Engine X",
    Availability: "Available to join in a month and 15 days",
  },
  {
    Title: "Project 62",
    Technologies: "Python, Django, Django Rest Framework",
    Frontend: "No information provided",
    Backend: "Python, Django, Django Rest Framework",
    Databases: "No information provided",
    Infrastructre: "No information provided",
    Availability:
      "Comfortable with working from Gurgaon office and is available to join within a month",
  },
  {
    Title: "Project 63",
    Technologies: "Lambda, AWS, API gateway, React",
    Frontend: "React, Redux",
    Backend: "Node.js, Python Django",
    Databases: "Not mentioned",
    Infrastructre: "AWS",
    Availability: "Can start in 30-60 days, comfortable relocating to Gurgaon",
  },
  {
    Title: "Project 64",
    Technologies: "Django, React, Alpha Vantage API",
    Frontend: "React",
    Backend: "Python Django",
    Databases: "Not mentioned",
    Infrastructre: "Not mentioned",
    Availability: "After January",
  },
  {
    Title: "Project 65",
    Technologies:
      "JavaScript, HTML, CSS, Google Fonts, React Icon, Responsiveness",
    Frontend: "React, TypeScript",
    Backend: "Node, Express",
    Databases: "Not Mentioned",
    Infrastructre: "Not Mentioned",
    Availability: "Immediate, comfortable working from office in Gurgaon",
  },
  {
    Title: "Project 66",
    Technologies: "Digital Marketing",
    Frontend: "React, Angular",
    Backend: "Node",
    Databases: "Not Mentioned",
    Infrastructre: "Not Mentioned",
    Availability: "Can join within a week and ready to move to Gurgaon",
  },
  {
    Title: "Project 67",
    Technologies: "React, Next JS, Node JS, Express, SQLite, MongoDB, Prisma",
    Frontend: "React, Next JS",
    Backend: "Node JS, Express",
    Databases: "SQLite, MongoDB, Prisma",
    Infrastructre: "Not Mentioned",
    Availability:
      "Available to join in 15 days and comfortable working from Gurgaon office",
  },
  {
    Title: "Project 68",
    Technologies: "Micro service architecture, Spring MVC, Spring Cloud",
    Frontend: "Interest in learning",
    Backend:
      "Java, Spring and Spring boot framework, REST APIs, micro services architecture",
    Databases: "Hadoop ecosystem",
    Infrastructre: "Micro services architecture",
    Availability:
      "Willing to join as soon as the interview process completes. Comfortable working from office in Gurgaon",
  },
  {
    Title: "Project 69",
    Technologies:
      "TypeScript, FCM token, Socket IO, Google Descriptive APIs, Natural Language Processing",
    Frontend: "Not specified",
    Backend: "Python",
    Databases: "Not specified",
    Infrastructre: "Not specified",
    Availability: "Not specified",
  },
  {
    Title: "Project 70",
    Technologies: "Python, AI, ML",
    Frontend: "React JS",
    Backend: "Django, Python",
    Databases: "Not specified",
    Infrastructre: "Not specified",
    Availability: "Immediate joiner",
  },
  {
    Title: "Project 71",
    Technologies:
      "Node JS, Express JS, MySQL, AWS, GitLab, Sonar, Swagger APIs",
    Frontend: "React",
    Backend: "Node.js, Express.js",
    Databases: "MongoDB, MySQL",
    Infrastructre: "AWS",
    Availability: "Immediate",
  },
  {
    Title: "Project 72",
    Technologies: "React JS, Akka microservices, Postgres, MongoDB, Sequel",
    Frontend: "Angular JS, React",
    Backend: "Scala, Akka, Play framework",
    Databases: "Postgres, MongoDB",
    Infrastructre: "Not specified",
    Availability: "available to join from 29th September 2023",
  },
  {
    Title: "Project 73",
    Technologies: "Amazon SQS, Kafka",
    Frontend: "Angular, React, Next js",
    Backend: "Python Django",
    Databases: "Unspecified",
    Infrastructre: "Docker",
    Availability: "28th October",
  },
  {
    Title: "Project 74",
    Technologies: "Postman, JUnit, threads, Jenkins, Docker",
    Frontend: "Angular, React, Next js",
    Backend: "Python Django, Spring Boot",
    Infrastructre: "Docker, Jenkins",
    Availability:
      "Available to join within 10-15 days and willing to relocate to Gurgaon",
  },
  {
    Title: "Project 75",
    Technologies: "Cron job",
    Frontend: "React",
    Backend: "Not specified",
    Databases: "Not specified",
    Infrastructre: "Not specified",
    Availability: "Can join immediately, comfortable with working from Gurgaon",
  },
  {
    Title: "Project 76",
    Technologies: "JavaScript",
    Frontend: "JavaScript, React",
    Backend: "JavaScript",
    Databases: "Not Discussed",
    Infrastructre: "Not Discussed",
    Availability:
      "Immediately, with a maximum of two weeks notice period at current job",
  },
  {
    Title: "Project 77",
    Technologies: "Django, Front-end and Back-end development",
    Frontend: "Basic knowledge",
    Backend: "Basic knowledge",
    Databases: "Not mentioned",
    Infrastructre: "Not mentioned",
    Availability:
      "Available to join within a week and comfortable working from office in Gurgaon",
  },
  {
    Title: "Project 78",
    Technologies: "ASP.NET, CSS, HTML, SQL Server",
    Frontend: "CSS, HTML, JavaScript, Ajax, Bootstrap",
    Backend: "ASP.NET MVC",
    Databases: "SQL Server",
    Infrastructre: "Not Mentioned",
    Availability:
      "Available to join within 10 days and comfortable with working from Gurgaon office.",
  },
  {
    Title: "Project 79",
    Technologies:
      "Java, WS, AWS, Lambda Functions, Cloud Watch, MongoDB, Express, React, Node JS",
    Frontend: "ReactJS",
    Backend: "NodeJS, ExpressJS",
    Databases: "MongoDB",
    Infrastructre: "AWS",
    Availability: "Immediate, ready to move to Gurgaon office",
  },
  {
    Title: "Project 80",
    Technologies: "EF Core API, Angular, Azure",
    Frontend: "Angular JS",
    Backend: ".Net, SQL",
    Databases: "SQL",
    Infrastructre: "Azure",
    Availability:
      "Available to join within 15 days and comfortable with working from Gurgaon office",
  },
  {
    Title: "Project 81",
    Technologies: "Machine learning, Linear regression",
    Frontend: "Undetermined",
    Backend: "Python, FAST API",
    Databases: "Undetermined",
    Infrastructre: "PyCharm",
    Availability:
      "Available to join immediately and willing to relocate to Gurgaon",
  },
  {
    Title: "Project 82",
    Technologies: "JavaScript, External Libraries",
    Frontend: "Angular, React, Next js",
    Backend: "Python",
    Databases: "Not Mentioned",
    Infrastructre: "Not Mentioned",
    Availability: "Immediately, ready to move to Gurgaon office",
  },
  {
    Title: "Project 83",
    Technologies: "Machine Learning, Cosine Similarity",
    Frontend: "React, HTML, CSS, JavaScript",
    Availability: "Available to join immediately",
  },
  {
    Title: "Project 84",
    Technologies: "React, Node, Express, MongoDB, PostgreSQL, Django, Python",
    Frontend: "React",
    Backend: "Node, Express, Django, Python",
    Databases: "MongoDB, PostgreSQL",
    Availability: "Can join within 1-2 weeks after receiving the offer letter",
  },
  {
    Title: "Project 85",
    Technologies: "MongoDB, Angular, JavaScript, CSS, HTML, Python",
    Frontend: "Angular, React, Next.js",
    Backend: "Python Django, Fast APIs, Notes",
    Databases: "MongoDB",
    Infrastructre: "Not Mentioned",
    Availability:
      "Available to join as soon as possible with a notice period of 30 days",
  },
  {
    Title: "Project 86",
    Technologies:
      "C++, Java, AWS, Spring Framework, J Unit, Machine Learning, Linux, AOP",
    Frontend: "JavaScript, React JS, HTML, CSS",
    Backend: "Node JS, Java, AWS, Spring Framework",
    Databases: "Not mentioned",
    Infrastructre: "AWS",
    Availability: "Available to join immediately",
  },
  {
    Title: "Project 87",
    Technologies:
      "Open AI, Machine Learning Models, Python Libraries for Audio Conversion and Prompt Engineering",
    Frontend: "4-5/10",
    Backend: "Python Django, 7-8/10",
    Databases: "Not Mentioned",
    Infrastructre: "Not Mentioned",
    Availability:
      "Available to join within a month and comfortable working from Gurgaon office",
  },
  {
    Title: "Project 88",
    Technologies: "Java, AWS Lambda",
    Frontend: "React",
    Backend: "Node.js, Express.js",
    Databases: "MongoDB",
    Infrastructre: "AWS",
    Availability: "Immediately",
  },
  {
    Title: "Project 89",
    Technologies: "MongoDB, Node JS, JavaScript, JWT, React Native",
    Frontend: "Reactjs, React Native",
    Backend: "Node.js, Express",
    Databases: "MongoDB, PostgreSQL",
    Infrastructre: "Knowledge not specified",
    Availability:
      "Can join immediately and is comfortable working from the Gurgaon office",
  },
  {
    Title: "Project 90",
    Technologies: "Pega, Python Node JS, Theme Cosmos",
    Frontend: "Python Node JS",
    Backend: "No prior experience with backend frameworks",
    Databases: "Not mentioned",
    Infrastructre: "Not mentioned",
    Availability: "Available to join immediately after the first meeting",
  },
  {
    Title: "Project 91",
    Technologies: "React, Next.js, Python Django, Node.js, Express.js",
    Frontend: "React, Next.js",
    Backend: "Python Django, Node.js, Express.js",
    Databases: "Unknown",
    Infrastructre: "Unknown",
    Availability: "Immediately, ready to move to Gurgaon office",
  },
  {
    Title: "Project 92",
    Technologies: "Machine Learning, Front-end and Backend Frameworks, AWS",
    Frontend: "Unknown",
    Backend: "Unknown",
    Databases: "Unknown",
    Infrastructre: "AWS",
    Availability: "Immediate",
  },
  {
    Title: "Project 93",
    Technologies: "JavaScript, HTML, CSS, Bootstrap, Express JS, Node JS",
    Frontend: "React, Redux, HTML, JavaScript, CSS, Bootstrap",
    Backend: "Express JS, Node JS",
    Databases: "MongoDB",
    Infrastructre: "Not provided",
    Availability:
      "Available to join as soon as possible. Comfortable with the requirement of working from Gurgaon office",
  },
  {
    Title: "Project 94",
    Technologies: "CSS, HTML, CSS, JavaScript, Python, MySQL",
    Frontend: "Angular, React, Next js",
    Backend: "No Experience",
    Databases: "MySQL",
    Infrastructre: "No Experience",
    Availability: "Available to join",
  },
  {
    Title: "Project 95",
    Technologies: "React JS, Redux, React Hooks",
    Frontend: "HTML, CSS, JavaScript, React JS",
    Backend: "Node JS, C&C",
    Databases: "Not provided",
    Infrastructre: "Not provided",
    Availability: "Available to join tomorrow",
  },
  {
    Title: "Project 96",
    Technologies: "React JS, Node.js",
    Frontend: "React JS",
    Backend: "Node.js (Learning)",
    Databases: "Not Mentioned",
    Infrastructre: "Not Mentioned",
    Availability:
      "Available to join within a week of being offered a position and willing to work from Gurgaon office",
  },
  {
    Title: "Project 97",
    Technologies: "Mongoose, React JS, Node JS",
    Frontend: "React JS",
    Backend: "Node JS",
    Databases: "Mongoose",
    Infrastructre: "Not Mentioned",
    Availability:
      "Available to join by 25th September, comfortable working from an office in Gurgaon",
  },
  {
    Title: "Project 98",
    Technologies: "Open pose, MRCP CNN, Pandas, scikit learn, Python",
    Frontend: "HTML, JavaScript, jQuery, CSS",
    Backend: "Python, Django",
    Databases: "MySQL, MSSQL",
    Infrastructre: "Not Mentioned",
    Availability:
      "Available to join immediately and willing to commute to Gurgaon",
  },
  {
    Title: "Project 99",
    Technologies:
      "React.js, Redux, Schema UI, Config one UI, Live Swiggy API, Conflict one UI",
    Frontend: "React.js",
    Backend: "Willing to learn",
    Databases: "Good understanding of data structures and algorithms",
    Infrastructre: "Not Mentioned",
    Availability: "Immediate, willing to relocate to Gurgaon",
  },
  {
    Title: "Project 100",
    Technologies: "Front-end and Back-end frameworks",
    Frontend: "7.5/10",
    Backend: "08-Oct",
    Databases: "Not Mentioned",
    Infrastructre: "Azure DevOps",
    Availability: "45 days notice period",
  },
  {
    Title: "Project 101",
    Technologies: "Angular",
    Frontend: "Angular, React",
    Backend: "Java Springboard",
    Databases: "Not mentioned",
    Infrastructre: "Not mentioned",
    Availability:
      "Available to join in 10 days and comfortable working from office in Gurgaon",
  },
  {
    Title: "Project 102",
    Technologies: "Web sockets, TCP IP handshake",
    Frontend: "React",
    Backend: "Express JS",
    Databases: "Not mentioned",
    Infrastructre: "Not mentioned",
    Availability: "Immediate joiner, ready to move to Gurgaon office",
  },
  {
    Title: "Project 103",
    Technologies: "Octa IDP",
    Frontend: "Angular",
    Backend: "Spring Boot",
    Databases: "Not mentioned",
    Infrastructre: "Not mentioned",
    Availability: "30 days after receiving the offer letter",
  },
  {
    Title: "Project 104",
    Technologies: "Node JS, Kafka, Java, Springboard, Postman",
    Frontend: "React",
    Backend: "Python Django",
    Databases: "Not Mentioned",
    Infrastructre: "Not Mentioned",
    Availability:
      "Immediately available and willing to work from Gurgaon office",
  },
  {
    Title: "Project 105",
    Technologies: "Node.js, MongoDB, Google APIs",
    Frontend: "React",
    Backend: "Node JS, Express JS",
    Databases: "MongoDB",
    Infrastructre: "AWS",
    Availability:
      "Available to join immediately and comfortable with working from Gurgaon office",
  },
  {
    Title: "Project 106",
    Technologies: "Elasticsearch, Dagger",
    Frontend: "React JS",
    Backend: "Django",
    Databases: "Not mentioned",
    Infrastructre: "Amazon's Taman Toolkit",
    Availability: "Immediate, willing to work from Gurgaon office",
  },
  {
    Title: "Project 107",
    Technologies: "Angular, React, Node JSC",
    Frontend: "Angular, React",
    Backend: "Node JSC, Django",
    Databases: "Not mentioned",
    Infrastructre: "Not mentioned",
    Availability: "End of August, comfortable with working from Gurgaon office",
  },
  {
    Title: "Project 108",
    Technologies:
      "Angular, Node, Nest, TypeScript, Azure, Open AI, REST APIs, RBAC",
    Frontend: "Angular, React, Next js",
    Backend: ".Net, Node.js",
    Databases: "Not Mentioned",
    Infrastructre: "Azure, OpenAI",
    Availability: "Available to join in 12 days after receiving offer letter",
  },
  {
    Title: "Project 109",
    Technologies: "React, Material UI",
    Frontend: "React JS",
    Backend: "Java/Spring MVC",
    Availability:
      "Immediately available and comfortable working from Gurgaon office",
  },
  {
    Title: "Project 110",
    Technologies:
      "React JS, JavaScript, Material UI, Context API, React Redux, Java, Spring Boot, Oracle, REST APIs",
    Frontend: "React JS, JavaScript, Material UI, Context API, React Redux",
    Backend: "Java, Spring Boot, Oracle, REST APIs",
    Databases: "Oracle",
    Infrastructre: "Not Mentioned",
    Availability:
      "Available to join in 3 months with a notice period of 3 months",
  },
  {
    Title: "Project 111",
    Technologies: "Python, REST APIs, Java Spring Boot, AWS Lambda",
    Frontend: "Angular, React, Next.js",
    Backend: "Python, REST APIs, Java Spring Boot",
    Databases: "MongoDB, MySQL, PostgreSQL",
    Infrastructre: "AWS Lambda",
    Availability:
      "Available to join immediately. Willing to relocate to Gurgaon",
  },
  {
    Title: "Project 112",
    Technologies: "Deep Learning, Reinforcement Learning",
    Frontend: "Reactjs",
    Backend: "Python, Django",
    Databases: "Not Mentioned",
    Infrastructre: "Not Mentioned",
    Availability: "Between October to December",
  },
  {
    Title: "Project 113",
    Technologies: "Python, DBMS, MongoDB, Express, Node JS, Reactjs",
    Frontend: "Reactjs",
    Backend: "Python, Node JS, Express",
    Databases: "DBMS, MongoDB",
    Infrastructre: "Experience in project deployment",
    Availability:
      "Available to join if offered a position and comfortable to work from office in Gurgaon",
  },
  {
    Title: "Project 114",
    Technologies:
      "BIRD base algorithm, Neutral Sofic Set, Voting Mechanism, Scraping Library",
    Frontend: "React JS",
    Backend: "Python, Flask, Node JS, AWS",
    Databases: "Not Mentioned",
    Infrastructre: "AWS",
    Availability: "Immediately",
  },
  {
    Title: "Project 115",
    Technologies: "Python, Beautiful Soup",
    Frontend: "Java Springboard",
    Backend: "Python Django",
    Databases: "Not mentioned",
    Infrastructre: "Not mentioned",
    Availability: "Available to join as soon as offered a position",
  },
  {
    Title: "Project 116",
    Technologies: "Django, Alpha Vantage API",
    Frontend: "React",
    Backend: "Flask",
    Databases: "Not mentioned",
    Infrastructre: "Not mentioned",
    Availability: "As soon as possible",
  },
  {
    Title: "Project 117",
    Technologies: "React, Bootstrap, HTML, Node.js, Rabbit MQ",
    Frontend: "React, Angular",
    Backend: "Node.js, Express",
    Databases: "Not Mentioned",
    Infrastructre: "Not Mentioned",
    Availability:
      "Can join in 18-15 days and comfortable working from Gurgaon office",
  },
  {
    Title: "Project 118",
    Technologies: "React, Angular, Next js, Python, Django",
    Frontend: "React, Angular, Next js",
    Backend: "Python, Django",
    Databases: "PostgreSQL",
    Infrastructre: "AWS",
    Availability: "Immediate, ready to move to Gurgaon office",
  },
  {
    Title: "Project 119",
    Technologies: "Java, AWS Lambda and other AWS services",
    Frontend: "React",
    Backend: "Node JS, Express",
    Databases: "MongoDB",
    Infrastructre: "AWS",
    Availability: "Within a week",
  },
  {
    Title: "Project 120",
    Technologies: "Jenkins, Serverless Architecture",
    Frontend: "Angular, React, Next js",
    Backend: "Python Django",
    Availability: "Can join in 30 days and willing to move to Gurgaon office",
  },
  {
    Title: "Project 121",
    Technologies: "Java, MySQL, Kafka, HTML, CSS",
    Frontend: "HTML, CSS",
    Backend: "Java",
    Databases: "MySQL",
    Infrastructre: "Kafka",
    Availability: "Immediate",
  },
  {
    Title: "Project 122",
    Technologies: "React, JS, HTML, CSS, JavaScript, Java, Spring Boot, MySQL",
    Frontend: "React, JS, HTML, CSS, JavaScript",
    Backend: "Java, Spring Boot",
    Databases: "MySQL",
    Infrastructre: "Not mentioned",
    Availability:
      "Available to join within 30-45 days, willing to work from the Gurgaon office",
  },
  {
    Title: "Project 123",
    Technologies: "Python, Django, PostgreSQL",
    Frontend: "React JS",
    Backend: "Python Django",
    Databases: "SQL & NoSQL",
    Infrastructre: "Not Mentioned",
    Availability: "After 14th November",
  },
  {
    Title: "Project 124",
    Technologies:
      "Angular, React, Node JS, Flask, Spring Boot, Robot Framework",
    Frontend: "Angular, React",
    Backend: "Node JS, Flask, Spring Boot",
    Databases: "Not Mentioned",
    Infrastructre: "Not Mentioned",
    Availability:
      "Available to join immediately, comfortable with working from Gurgaon office",
  },
  {
    Title: "Project 125",
    Technologies: "Python, Cosine Similarity Algorithm",
    Frontend: "Angular",
    Backend: "Spring MVC",
    Databases: "Not Mentioned",
    Infrastructre: "Not Mentioned",
    Availability:
      "Available to join within 15 days, and comfortable with the arrangement of working from Gurgaon office",
  },
  {
    Title: "Project 126",
    Technologies:
      "HTML5, CSS3, JavaScript, React JS, Node JS, Express JS, SQL, MongoDB",
    Frontend: "HTML5, CSS3, JavaScript, React JS",
    Backend: "Node JS, Express JS",
    Databases: "SQL, MongoDB",
    Infrastructre:
      "Has experience with transitioning from MySQL to MongoDB and integrating Node JS",
    Availability: "Immediate joiner, comfortable working from Gurgaon office",
  },
  {
    Title: "Project 127",
    Technologies: "Docker, Microservices",
    Frontend: "React",
    Backend: "Not Mentioned",
    Databases: "Not Mentioned",
    Infrastructre: "Docker",
    Availability: "Available to join after 30 days notice period",
  },
  {
    Title: "Project 128",
    Technologies: "Python, JavaScript, CC, ReactJS",
    Frontend: "ReactJS",
    Backend: "Python, Node.js",
    Databases: "Not Mentioned",
    Infrastructre: "Not Mentioned",
    Availability: "Comfortable working from Gurgaon office",
  },
  {
    Title: "Project 129",
    Technologies: "React, Node.js, Postman",
    Frontend: "React",
    Backend: "Node.js",
    Databases: "MongoDB",
    Infrastructre: "Unknown",
    Availability:
      "Available to join from 1 October and comfortable with working from Gurgaon office.",
  },
  {
    Title: "Project 130",
    Technologies: "CNN, various libraries",
    Frontend: "Theoretical knowledge",
    Backend: "Theoretical knowledge",
    Databases: "Not specified",
    Infrastructre: "Not specified",
    Availability:
      "Can join immediately, comfortable working from Gurgaon office",
  },
  {
    Title: "Project 131",
    Technologies: "Python",
    Frontend: "Not Mentioned",
    Backend: "Not Mentioned",
    Databases: "Not Mentioned",
    Infrastructre: "Not Mentioned",
    Availability: "Immediately",
  },
  {
    Title: "Project 132",
    Technologies: "Mask R-CNN, Python",
    Frontend: "HTML, CSS, Angular, React",
    Backend: "Node JavaScript, Python Django",
    Databases: "DBMS",
    Infrastructre: "Not mentioned",
    Availability:
      "Available to join the role the next day after receiving the offer",
  },
  {
    Title: "Project 133",
    Technologies: "Open AI, TypeScript",
    Frontend: "Angular, Ionic",
    Backend: "Node JS, Python Django",
    Databases: "Not mentioned",
    Infrastructre: "Not mentioned",
    Availability: "Within 12 days",
  },
  {
    Title: "Project 134",
    Technologies: "React, JS, JavaScript, Python, C",
    Frontend: "React",
    Backend: "Node.js, Express.js, Python Django",
    Databases: "MongoDB",
    Availability: "Available to join immediately, ready to relocate to Gurgaon",
  },
  {
    Title: "Project 135",
    Technologies:
      "React, Next.js, Node.js, Facebook and Google authentication, dynamic GraphQL queries",
    Frontend: "React, Next.js",
    Backend: "Node.js",
    Databases: "Not Mentioned",
    Infrastructre: "Not Mentioned",
    Availability: "Available to join from 1st November",
  },
  {
    Title: "Project 136",
    Technologies: "Steamboat, Java",
    Frontend: "React",
    Backend: "Java",
    Databases: "Not mentioned",
    Infrastructre: "Docker, Jenkins",
    Availability: "10-15 days",
  },
  {
    Title: "Project 137",
    Technologies: "Java",
    Frontend: "Not mentioned",
    Backend: "Java",
    Databases: "Not mentioned",
    Infrastructre: "Not mentioned",
    Availability:
      "Can join after 30 days of notice period and is comfortable with working from Gurgaon office",
  },
  {
    Title: "Project 138",
    Technologies: "AWS, PubSub, Dagger, Java",
    Frontend: "ReactJS",
    Backend: "Java",
    Databases: "Not mentioned",
    Infrastructre: "AWS",
    Availability: "Immediate joiner, willing to work from Gurgaon office",
  },
  {
    Title: "Project 139",
    Technologies: "React, Jest, Jenkins",
    Frontend: "React",
    Backend: "Not Mentioned",
    Databases: "Not Mentioned",
    Infrastructre: "Not Mentioned",
    Availability:
      "Available to join in one month after offer. Comfortable with working from Gurgaon office.",
  },
  {
    Title: "Project 140",
    Technologies: "React, Firebase",
    Frontend: "React",
    Backend: "Firebase",
    Databases: "Firebase",
    Infrastructre: "Not Mentioned",
    Availability: "Immediate, ready to work from Gurgaon",
  },
  {
    Title: "Project 141",
    Technologies: "React, Next.js, Node.js, Express",
    Frontend: "React, Next.js",
    Backend: "Node.js, Express",
    Databases: "Not mentioned",
    Infrastructre: "Not mentioned",
    Availability:
      "Immediately available and comfortable with relocating to Gurgaon",
  },
  {
    Title: "Project 142",
    Technologies: "LSTM model, overfitting techniques",
    Frontend: "Angular, React, Next JS",
    Backend: "Rating is 6/10",
    Databases: "Not mentioned",
    Infrastructre: "Not mentioned",
    Availability: "Immediate if remote, January 2024 if office work",
  },
  {
    Title: "Project 143",
    Technologies: "React JS, MSGS JavaScript, TypeScript, Django, Spring Boot",
    Frontend: "React JS",
    Backend: "Node JS, Django, Spring Boot",
    Availability:
      "60 days notice period, comfortable with working in Gurgaon office",
  },
  {
    Title: "Project 144",
    Technologies: "React, JavaScript, Open Source Weather API",
    Frontend: "React, JavaScript, HTML, CSS",
    Backend: "Node.js",
    Databases: "Not mentioned",
    Infrastructre: "Not mentioned",
    Availability: "Available to join immediately within 1-4 days",
  },
  {
    Title: "Project 145",
    Technologies: "React, Python, Django, Flask, REST APIs, Fast APIs, Docker",
    Frontend: "React, Angular",
    Backend: "Python, Django",
    Infrastructre: "Docker",
    Availability: "Immediate",
  },
  {
    Title: "Project 146",
    Technologies:
      "React, JS, Angular, Python, Django, API integration, Docker, Agile methodology",
    Frontend: "React, Angular",
    Backend: "Python, Django",
    Databases: "Not Mentioned",
    Infrastructre: "Docker, Agile methodology",
    Availability: "Immediate joiner, willing to work from Gurgaon office",
  },
  {
    Title: "Project 147",
    Technologies: "Reactjs, Angular, Python, Django, Docker",
    Frontend: "React, Angular",
    Backend: "Python Django",
    Databases: "Not Mentioned",
    Infrastructre: "Docker",
    Availability: "Immediate",
  },
  {
    Title: "Project 148",
    Technologies: "Python, MySQL",
    Frontend: "HTML, CSS, JavaScript, Reactjs, Bootstrap",
    Backend: "Python, Java",
    Databases: "MySQL",
    Infrastructre: "Azure, Docker, Linux, Git",
    Availability: "From 21 September 2023 and ready to move to Gurgaon office",
  },
  {
    Title: "Project 149",
    Technologies: "APIs",
    Frontend: "React, Next.js",
    Backend: "Not specified",
    Databases: "Not specified",
    Infrastructre: "Not specified",
    Availability: "One month notice period",
  },
  {
    Title: "Project 150",
    Technologies: "React, Angular, Python Django, REST APIs, payment gateway",
    Frontend: "React, Angular",
    Backend: "Python Django",
    Databases: "Not mentioned",
    Infrastructre: "Not mentioned",
    Availability: "Immediate",
  },
  {
    Title: "Project 151",
    Technologies: "Neural networks, ANN algorithm",
    Frontend: "React, Next JS, Angular",
    Backend: "Node JS, Ninjas, Django",
    Databases: "Not Mentioned",
    Infrastructre: "Not Mentioned",
    Availability:
      "Can join within one month of receiving the offer letter and is comfortable with working from the office in Gurgaon",
  },
];
